# Webhook CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: certmanager-linkerd-webhook-ss-issuer
spec:
  selfSigned: {}
---
# Made a certificate so we can reference it from the HelmRelease
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certmanager-linkerd-webhook-root
spec:
  isCA: true
  commonName: root.webhook.linkerd.cluster.local
  secretName: certmanager-linkerd-webhook-root
  duration: 87660h
  renewBefore: 24h
  usages:
    - server auth
    - client auth
    - cert sign
    - crl sign
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: certmanager-linkerd-root-ss-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: certmanager-linkerd-webhook-issuer
spec:
  ca:
    secretName: certmanager-linkerd-webhook-root
---
# Webhooks
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: certmanager-linkerd-webhook-issuer
    kind: Issuer
  commonName: linkerd-proxy-injector.linkerd.svc
  dnsNames:
  - linkerd-proxy-injector.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-k8s-tls
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: certmanager-linkerd-webhook-issuer
    kind: Issuer
  commonName: linkerd-sp-validator.linkerd.svc
  dnsNames:
  - linkerd-sp-validator.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth