# Webhook CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: certmanager-linkerd-viz-webhook-ss-issuer
spec:
  selfSigned: {}
---
# Made a certificate so we can reference it from the HelmRelease
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certmanager-linkerd-viz-webhook-root
spec:
  isCA: true
  commonName: root.webhook.viz.linkerd.cluster.local
  secretName: certmanager-linkerd-viz-webhook-root
  duration: 87660h
  renewBefore: 24h
  usages:
    - server auth
    - client auth
    - cert sign
    - crl sign
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: certmanager-linkerd-viz-webhook-ss-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: certmanager-linkerd-viz-webhook-issuer
spec:
  ca:
    secretName: certmanager-linkerd-viz-webhook-root
---
# Certs for Tap
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap
  namespace: linkerd-viz
spec:
  secretName: tap-k8s-tls
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: certmanager-linkerd-viz-webhook-issuer
    kind: Issuer
  commonName: tap.linkerd-viz.svc
  dnsNames:
  - tap.linkerd-viz.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-tap-injector
  namespace: linkerd-viz
spec:
  secretName: tap-injector-k8s-tls
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: certmanager-linkerd-viz-webhook-issuer
    kind: Issuer
  commonName: tap-injector.linkerd-viz.svc
  dnsNames:
  - tap-injector.linkerd-viz.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth