apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  interval: 5m
  install:
    remediation:
      retries: 300
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  values:
    installNamespace: false
    tap:
      externalSecret: true
    tapInjector:
      externalSecret: true
  valuesFrom:
    - kind: Secret
      name: certmanager-linkerd-viz-webhook-root
      valuesKey: tls.crt
      targetPath: "tap.caBundle"
    - kind: Secret
      name: certmanager-linkerd-viz-webhook-root
      valuesKey: tls.crt
      targetPath: "tapInjector.caBundle"
